### ISSUE TITLE
old builds are not being deleted

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#211] opened 2016-04-20 23:13 UTC
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [*] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [*] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [*] You've ran `composer install --no-dev` from the root of your installation.
- [*] You've ran `npm install --production` from the root of your installation.
- [] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Previous builds should be removed from server

### Actual behaviour

it keep on adding new builds so server running out of space.

when checked, it has 44 builds totally and taking up 6.1GB space :cry: 

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

### Environment info
Operating System:
PHP Version:
Node Version:
Database System:
Database Version:

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by REBELinBLUE** [comment] 2016-04-21 22:38
Sorry, been a bit busy lately having started a new job so things have kind of falling by the wayside. I shall investigate tomorrow evening

Can you go into Admin > Projects and edit the project and see what you have the "Builds to keep" setting set to?

**Comment by lorvent** [comment] 2016-04-22 01:03
Hi,
congrats on the new job :boom: 
Currently it has set to 10.

---
I have checked all repos and some have as many as 85 builds

**Comment by lorvent** [comment] 2016-04-22 15:44
On a side note, today we ran our 1000th build after 80days of usage,
so i am highly thankful to you for this wonderful product :100: 

![wow](https://media.giphy.com/media/3o7abBP0nMjrdIvaCY/giphy.gif)

**Comment by REBELinBLUE** [comment] 2016-04-22 15:52
Awesome!

Are there any logs in the "Purge Old Releases" step in any of the recent deployments?

Can you try running

```bash
$ (ls -t|head -n 10;ls)|sort|uniq -u)
```

in the "builds" directory for one of the projects and paste the output?

Also, can you check if the `xargs` command exists? I've never heard of a system without it but you never know

**Comment by lorvent** [comment] 2016-04-22 16:12
i don't see logs for any of deployment.

that command shows me error

```parse error near```

**Comment by REBELinBLUE** [comment] 2016-04-22 16:21
Sorry, extra bracket at the end, should be

```bash
$ (ls -t|head -n 10;ls)|sort|uniq -u
```

**Comment by lorvent** [comment] 2016-04-22 16:30
please check,

20160401191636
20160402094826
20160404193447
20160405075231
20160405100514
20160405101427
20160409093227
20160409195323
20160412120657
20160412215418
20160414220047
20160415094309
20160416104723
20160418112601
20160418112700
20160418210719
20160418233353
20160419112801
20160420000428
20160420000804
20160420001155
20160420001323
20160420001704
20160420002038
20160420002254
20160420003110
20160420003516
20160420004335
20160420004709
20160420070330
20160420070820
20160420071215

**Comment by alsotop** [comment] 2016-04-22 16:40
As a side, I've noticed on our deploys that if our software creates files with a different permission (our offending tool was our less compiler) then deployer might fail to remove the files, and thus leave some release folders.

**Comment by lorvent** [comment] 2016-04-22 16:43
hmm.... then how to solve that problem?

**Comment by REBELinBLUE** [comment] 2016-04-22 16:53
Hmm, very interesting that you have no log output

Have the deployments been marked as "Completed with errors". Failure to delete builds won't cause a "Failed" deployment as it would have been activated by that stage, however in that case I would expect there to be some message in the log saying what the problem is

**Comment by REBELinBLUE** [comment] 2016-04-22 16:55
Can you try

```bash
$ (ls -t|head -n 11;ls)|sort|uniq -u||xargs rm -rf
```

That SHOULD delete the builds, it is what deployer runs. Interested to see if you get any output when doing it manually.

Notice that the number has increased from 10 to 11, that is what deployer does so that it keeps the new build and the 10 previous builds

**Comment by REBELinBLUE** [comment] 2016-04-22 17:07
Sorry, I realise when I say log you may have thought I meant a log file. I meant the button on the right hand side of this screen

![](https://camo.githubusercontent.com/66b962b52868247d52457cd67991943facc5b0a7/687474703a2f2f7777772e726562656c696e626c75652e636f6d2f6465706c6f7965722f6465706c6f796d656e742e706e67)

**Comment by lorvent** [comment] 2016-04-22 17:12
```
20160401191636
20160402094826
20160404193447
20160405075231
20160405100514
20160405101427
20160409093227
20160409195323
20160412120657
20160412215418
20160414220047
20160415094309
20160416104723
20160418112601
20160418112700
20160418210719
20160418233353
20160419112801
20160420000428
20160420000804
20160420001155
20160420001323
20160420001704
20160420002038
20160420002254
20160420003110
20160420003516
20160420004335
20160420004709
20160420070330
20160420070820
```

thats the output but builds are not deleted ```ls``` shows me all those again

and yes, i mean in deployment page only but i don't see any log against "Purge old releases"

**Comment by REBELinBLUE** [comment] 2016-04-22 19:27
Crap I've done it again, sorry typo in the previous command, should be

```bash
$ (ls -t|head -n 11;ls)|sort|uniq -u|xargs rm -rf
```

**Comment by lorvent** [comment] 2016-04-22 19:42
that seems to delete all builds except last 10

**Comment by REBELinBLUE** [comment] 2016-04-22 19:47
Hmm, so it works when running manually, that is odd :|

**Comment by lorvent** [comment] 2016-04-22 19:58
hmm,
deployer is one server, target is another server..... is that causing problem?

**Comment by REBELinBLUE** [comment] 2016-04-22 20:01
No, connects to the targer server via SSH and runs commands

**Comment by REBELinBLUE** [comment] 2016-04-24 17:07
Do you have a log in storage/logs/ ? It should contain the commands run on a deployment.

Could you maybe supply a copy of your DB?

**Comment by lorvent** [comment] 2016-04-24 18:17
I just sent you logs, db over mail,
please let me know if you received them.

**Comment by REBELinBLUE** [comment] 2016-04-24 18:23
Got them thanks, will try and take a look at that this evening, otherwise tomorrow

**Comment by REBELinBLUE** [comment] 2016-04-24 18:50
Hey, both the zip files are the DB dump

**Comment by lorvent** [comment] 2016-04-24 18:52
Hey sorry....
i have sent you logs now.

**Comment by lorvent** [comment] 2016-04-25 22:01
God.... this problem looks bigger than i though of

today one site failed to load then i found all the builds ate up all the space :(

![image](https://cloud.githubusercontent.com/assets/3512953/14800431/a89b9de4-0b0f-11e6-8bb3-c0fa981b45a1.png)

**Comment by REBELinBLUE** [comment] 2016-04-26 12:28
@dancryer has confirmed he has the problem also, still trying to recreate it. Really weird

**Comment by REBELinBLUE** [comment] 2016-04-26 13:27
Found the problem, will fix it when I get home from work and release a new version

Needless to say, I'm an idiot

**Comment by lorvent** [comment] 2016-04-26 16:55
Hey....

you are a great guy producing something great... don't feel bad for one single bug...

I really appreciate your work.....

you may know or not....i visit this page repo so often that its one of 8 thumbnails in my chrome ;) and you are saving literally many hours of many devs for manually logging in and git pulling.

**Closed** 2016-04-26 22:09 UTC
Labels: Bug, Context: Console/Jobs, Priority: High
